# To build:
#   docker build -f Dockerfile-test.gpu-cuda-10 -t gocv-test-gpu-cuda-10 .
#
# To run tests:
#   xhost +
#   docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --gpus all gocv-test-gpu-cuda-10
#   xhost -
#
FROM gocv/opencv:4.5.2-gpu-cuda-10 AS gocv-gpu-test-cuda-10

ENV GOPATH /go

COPY . /go/src/gocv.io/x/gocv/

WORKDIR /go/src/gocv.io/x/gocv

RUN go get -u github.com/rakyll/gotest

ENTRYPOINT ["gotest", "-v", ".", "./contrib/...", "./cuda/..."]
