# To build:
#   docker build -f Dockerfile-test -t gocv-test .
#
# To run tests:
#   xhost +
#   docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix gocv-test-4.x
#   xhost -
#
FROM ghcr.io/hybridgroup/opencv:4.11.0 AS gocv-test-4.11

ENV GOPATH /go

COPY . /go/src/gocv.io/x/gocv/

WORKDIR /go/src/gocv.io/x/gocv

RUN go install github.com/rakyll/gotest@latest

ENTRYPOINT ["gotest", "-v", ".", "./contrib/..."]
