# To build:
#   docker build -f Dockerfile-test.gpu-cuda-11 -t gocv-test-gpu-cuda-11 .
#
# To run tests:
#   docker run -it --rm --gpus all gocv-test-gpu-cuda-11
#
FROM gocv/opencv:4.5.3-gpu-cuda-11 AS gocv-gpu-test-cuda-11

ENV GOPATH /go
ENV PATH="${PATH}:/go/bin"

COPY . /go/src/gocv.io/x/gocv/

WORKDIR /go/src/gocv.io/x/gocv

RUN go get -u github.com/rakyll/gotest

ENTRYPOINT ["gotest", "-v", "./cuda/..."]
