# to build this docker image:
#   docker build -f Dockerfile-test.gpu .
FROM gocv/opencv:4.5.2-gpu AS gocv-gpu-test

ENV GOPATH /go

COPY . /go/src/gocv.io/x/gocv/

WORKDIR /go/src/gocv.io/x/gocv
RUN go build -tags example -o /build/gocv_cuda_version ./cmd/cuda/

ENTRYPOINT ["go", "test", "-v", "./cuda/..."]
