# to build:
#   docker build -f Dockerfile.opencv-openvino \
#     -t ghcr.io/hybridgroup/opencv:5.0.0-openvino .

FROM openvino/ubuntu20_dev:2022.1.0 AS opencv-openvino-base

LABEL maintainer="hybridgroup"
ENV DEBIAN_FRONTEND=noninteractive

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    git build-essential cmake pkg-config unzip \
    wget curl ca-certificates libcurl4-openssl-dev libssl-dev \
    libgtk2.0-dev \
    libavcodec-dev libavformat-dev libswscale-dev \
    libtbb2 libtbb-dev \
    libharfbuzz-dev libfreetype6-dev \
    libjpeg-dev libpng-dev libtiff-dev libdc1394-22-dev \
    nasm && \
    rm -rf /var/lib/apt/lists/*

ARG OPENCV_VERSION="5.0.0"
ENV OPENCV_VERSION=${OPENCV_VERSION}

ARG OPENCV_FILE="https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip"
ENV OPENCV_FILE=${OPENCV_FILE}

ARG OPENCV_CONTRIB_FILE="https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.zip"
ENV OPENCV_CONTRIB_FILE=${OPENCV_CONTRIB_FILE}

RUN curl -Lo opencv.zip ${OPENCV_FILE} && \
    unzip -q opencv.zip && \
    curl -Lo opencv_contrib.zip ${OPENCV_CONTRIB_FILE} && \
    unzip -q opencv_contrib.zip && \
    rm opencv.zip opencv_contrib.zip && \
    cd opencv-${OPENCV_VERSION} && \
    mkdir build && cd build && \
    cmake \
      -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-${OPENCV_VERSION}/modules \
      -D OPENCV_ENABLE_NONFREE=ON \
      -D OPENCV_GENERATE_PKGCONFIG=ON \
      -D CMAKE_CXX_STANDARD=17 \
      -D WITH_IPP=OFF \
      -D WITH_OPENGL=OFF \
      -D WITH_QT=OFF \
      -D WITH_FREETYPE=ON \
      -D WITH_JASPER=OFF \
      -D WITH_TBB=ON \
      -D WITH_OPENVINO=ON \
      -D BUILD_opencv_gapi=OFF \
      -D ENABLE_FAST_MATH=ON \
      -D BUILD_JPEG=ON \
      -D WITH_SIMD=ON \
      -D ENABLE_LIBJPEG_TURBO_SIMD=ON \
      -D BUILD_DOCS=OFF \
      -D BUILD_EXAMPLES=OFF \
      -D BUILD_TESTS=OFF \
      -D BUILD_PERF_TESTS=ON \
      -D BUILD_opencv_java=NO \
      -D BUILD_opencv_python=NO \
      -D BUILD_opencv_python2=NO \
      -D BUILD_opencv_python3=NO \
      .. && \
    make -j"$(nproc)" && \
    make install && \
    ldconfig && \
    cd / && rm -rf opencv*

FROM opencv-openvino-base AS opencv-openvino-golang

ENV GO_RELEASE=1.25.5

RUN wget https://dl.google.com/go/go${GO_RELEASE}.linux-amd64.tar.gz && \
    tar xfv go${GO_RELEASE}.linux-amd64.tar.gz -C /usr/local && \
    rm go${GO_RELEASE}.linux-amd64.tar.gz

ENV PATH="${PATH}:/usr/local/go/bin"

ENV OPENVINO_DIR=/opt/intel/openvino_2022.1.0.643
ENV CGO_CXXFLAGS="-I/opt/intel/openvino_2022.1.0.643/runtime/include -I/opt/intel/openvino_2022.1.0.643/runtime/include/ie"
ENV CGO_LDFLAGS="-L/opt/intel/openvino_2022.1.0.643/runtime/lib/intel64 -lopenvino"
ENV LD_LIBRARY_PATH="/opt/intel/openvino_2022.1.0.643/runtime/lib/intel64:/opt/intel/openvino_2022.1.0.643/runtime/3rdparty/tbb/lib:${LD_LIBRARY_PATH}"

USER openvino

CMD ["go", "version"]