#   docker build -f Dockerfile-test.gpu-cuda-10 -t gocv-test-gpu-cuda-10 .
FROM gocv/opencv:4.5.2-gpu-cuda-10 AS gocv-gpu-test-cuda-10

ENV GOPATH /go

COPY . /go/src/gocv.io/x/gocv/

WORKDIR /go/src/gocv.io/x/gocv
RUN go build -tags example -o /build/gocv_cuda_version ./cmd/cuda/

ENTRYPOINT ["go", "test", "-v", "./cuda/..."]
