# To build:
#   docker build -f Dockerfile-test.gpu-cuda-12 -t gocv-test-gpu-cuda-12 .
#
# To run tests:
#   docker run -it --rm --gpus all gocv-test-gpu-cuda-12
#
FROM ghcr.io/hybridgroup/opencv:4.10.0-gpu-cuda-12 AS gocv-gpu-test-cuda-12

ENV GOPATH /go
ENV PATH="${PATH}:/go/bin"

COPY . /go/src/gocv.io/x/gocv/

WORKDIR /go/src/gocv.io/x/gocv

RUN go install github.com/rakyll/gotest@latest

ENTRYPOINT ["gotest", "-v", "./cuda/..."]
