# To build:
#   docker build -f Dockerfile-test -t gocv-test-4.x .
#
# To run tests:
#   xhost +
#   docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix gocv-test-4.x
#   xhost -
#
FROM gocv/opencv:4.7.0-dev AS gocv-test-4.x

ENV GOPATH /go

COPY . /go/src/gocv.io/x/gocv/

WORKDIR /go/src/gocv.io/x/gocv

RUN go install github.com/rakyll/gotest@latest

ENTRYPOINT ["gotest", "-v", ".", "./contrib/..."]
