# to build this docker image:
#   docker build -f Dockerfile.gpu .
FROM ghcr.io/hybridgroup/opencv:4.11.0-gpu-cuda-11 AS gocv-gpu

ENV GOPATH /go

COPY . /go/src/gocv.io/x/gocv/

WORKDIR /go/src/gocv.io/x/gocv
RUN go build -tags cuda -o /build/gocv_cuda_version ./cmd/cuda/

CMD ["/build/gocv_cuda_version"]
