# To build:
#   docker build -f Dockerfile-test -t gocv-test .
#
# To run tests:
#   xhost +
#   docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix gocv-test
#   xhost -
#
FROM gocv/opencv:4.5.4 AS gocv-test

ENV GOPATH /go

COPY . /go/src/gocv.io/x/gocv/

WORKDIR /go/src/gocv.io/x/gocv

RUN go get -u github.com/rakyll/gotest

ENTRYPOINT ["gotest", "-v", ".", "./contrib/..."]
