# to build this docker image:
#   docker build -f Dockerfile-test.gpu-cuda-11 -t gocv-test-gpu-cuda-11 .
FROM gocv/opencv:4.5.2-gpu-cuda-11 AS gocv-gpu-test-cuda-11

ENV GOPATH /go

COPY . /go/src/gocv.io/x/gocv/

WORKDIR /go/src/gocv.io/x/gocv

ENTRYPOINT ["go", "test", "-v", "./cuda/..."]